FROM python:3.12-slim-bookworm

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.3.3 /uv /bin/uv

# Install the project with intermediate layers
ADD .dockerignore .

# First, install the dependencies
WORKDIR /app
ADD uv.lock /app/uv.lock
ADD pyproject.toml /app/pyproject.toml
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project

ADD . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

ENV PATH="/app/.venv/bin:$PATH"

RUN python3 -m nltk.downloader punkt_tab

EXPOSE 8000

CMD ["fastapi", "run", "--host", "0.0.0.0", "src/search_api/api.py", "--port", "8000"]
