FROM python:3.12
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PATH="/opt/dagster/app/.venv/bin:$PATH"
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME /opt/dagster/app
COPY dagster.yaml $DAGSTER_HOME

WORKDIR /opt/dagster/app



COPY uv.lock pyproject.toml .env README.md ./
COPY bm25 ./bm25

RUN uv sync --frozen --no-install-project --link-mode=copy
RUN python -c "import nltk;nltk.download('punkt_tab')"
