[datastore]
index_name = "data-catalogue"
host = "https://data-catalogue-qjckkzu.svc.aped-4627-b74a.pinecone.io"
embed_model = "text-embedding-3-small"
embed_dim = 1536
chunk_size = 1024
chunk_overlap = 32

[model]
llm = "gpt-4o-mini"
top_k = 500
alpha = 0.75
